# Overwrites for Detekt
# Example for most configs: https://github.com/detekt/detekt/blob/main/config/detekt/detekt.yml
# Docs: https://detekt.dev/docs/intro
style:
  # using 5 instead of 2
  ReturnCount:
    active: true
    excludeGuardClauses: true
    max: 5
  MagicNumber:
    ignoreAnnotation: true

complexity:
  TooManyFunctions:
    excludes: ['**/extension/**', '**/test/**', '**/functionalTest/**']
    thresholdInFiles: 30
    thresholdInClasses: 30
    thresholdInInterfaces: 30

performance:
  # disabled since Kotlin compiler optimizations since 1.1.60
  SpreadOperator:
    active: false
