ext {
    publishArtifactId = "bdd-cucumber-gherkin-lib-core"
    publishDescription = "Core module for bdd-cucumber-gherkin-lib"
}

dependencies {
    // --- Spring
    implementation(libs.spring.boot)
    implementation(libs.spring.web)
    implementation(libs.spring.boot.test)

    // --- Logging
    implementation(libs.logging.logger)

    // --- Jackson
    implementation(libs.bundles.jackson)

    // Testing
    api(libs.bundles.cucumber)
    api(libs.json.path)
    api(libs.json.unit)
    implementation(libs.testing.kotlin.test)
}
